# Generated by Django 5.2.15 on 2026-06-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('read_time', models.CharField(default='3 mins', max_length=50)),
                ('focus_area', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(default='Medium', max_length=50)),
                ('content_json', models.JSONField(default=dict)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.questionbank')),
            ],
        ),
    ]
