# Generated by Django 5.2.15 on 2026-06-15 19:56

from django.db import migrations


def run_import_script(apps, schema_editor):
    import sys
    import os
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if BASE_DIR not in sys.path:
        sys.path.append(BASE_DIR)
    
    SubjectSummary = apps.get_model('core', 'SubjectSummary')
    SubjectSummary.objects.all().delete()
    
    import import_summaries
    import_summaries.run_import()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subjectsummary'),
    ]

    operations = [
        migrations.RunPython(run_import_script),
    ]
